# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title:
  en: CryptoCurrencies for the average guy.
  es: CryptoCurrencies para la gente normal.
desc:
  en: Make free money with crypto airdrops.
  es: Gana dinero gratis con los airdrops de crypto monedas.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://cryptoauntie.com" # the base hostname & protocol for your site
multilingual:
  more:
    en: Read More...
    es: Leer Mas...
collections:
  airdrops:
    output: true
# Build settings
markdown: kramdown
